apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pooja-invitation-hpa
  namespace: pooja-invitation
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pooja-invitation
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
